# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM gcc:13-bookworm AS build
WORKDIR /src
ARG CFLAGS_PROFILE=pre10b
ARG RINHA_ENABLE_METRICS=1

COPY Makefile ./
COPY include ./include
COPY src ./src

RUN make clean && make all CFLAGS_PROFILE=${CFLAGS_PROFILE} RINHA_ENABLE_METRICS=${RINHA_ENABLE_METRICS}

FROM debian:bookworm-slim AS runtime
WORKDIR /app

COPY --from=build /src/build/rinha-api /app/rinha-api
COPY release/kdprimary2.bin /app/resources/kdprimary2.bin

ENV RINHA_ADDR=:8080
ENV RINHA_LISTEN_MODE=fdpass
ENV RINHA_SEARCH_IMPL=kdprimary2
ENV RINHA_KDPRIMARY2_PATH=/app/resources/kdprimary2.bin
ENV RINHA_KDPRIMARY2_TOUCH=true
ENV RINHA_EXEC_MODE=epoll
ENV RINHA_API_PROCESSES=1
ENV RINHA_METRICS_ENABLED=false

EXPOSE 8080
ENTRYPOINT ["/app/rinha-api"]
