services:
  lb:
    image: ghcr.io/arturlbg/rinha-backend-2026-c:fdlb
    platform: linux/amd64
    ports:
      - "9999:9999"
    environment:
      RINHA_LB_ADDR: ":9999"
      RINHA_FDPASS_UPSTREAMS: "/sockets/api1.ctrl,/sockets/api2.ctrl"
      RINHA_LB_CONNECT_RETRY_MS: "25"
      RINHA_LB_STARTUP_TIMEOUT_MS: "10000"
    volumes:
      - sockets:/sockets
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    cpus: "0.05"
    mem_limit: 16m
    networks:
      - rinha

  api1:
    image: ghcr.io/arturlbg/rinha-backend-2026-c:kdprimary2-l64
    platform: linux/amd64
    user: "0:0"
    environment:
      RINHA_LISTEN_MODE: "fdpass"
      RINHA_UNIX_SOCKET: "/sockets/api1.ctrl"
      RINHA_SEARCH_IMPL: "kdprimary2"
      RINHA_KDPRIMARY2_PATH: "/app/resources/kdprimary2.bin"
      RINHA_KDPRIMARY2_TOUCH: "true"
      RINHA_EXEC_MODE: "epoll"
      RINHA_METRICS_ENABLED: "false"
    volumes:
      - sockets:/sockets
    healthcheck:
      test: ["CMD-SHELL", "test -S /sockets/api1.ctrl"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 1s
    cpus: "0.475"
    mem_limit: 167m
    networks:
      - rinha

  api2:
    image: ghcr.io/arturlbg/rinha-backend-2026-c:kdprimary2-l64
    platform: linux/amd64
    user: "0:0"
    environment:
      RINHA_LISTEN_MODE: "fdpass"
      RINHA_UNIX_SOCKET: "/sockets/api2.ctrl"
      RINHA_SEARCH_IMPL: "kdprimary2"
      RINHA_KDPRIMARY2_PATH: "/app/resources/kdprimary2.bin"
      RINHA_KDPRIMARY2_TOUCH: "true"
      RINHA_EXEC_MODE: "epoll"
      RINHA_METRICS_ENABLED: "false"
    volumes:
      - sockets:/sockets
    healthcheck:
      test: ["CMD-SHELL", "test -S /sockets/api2.ctrl"]
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 1s
    cpus: "0.475"
    mem_limit: 167m
    networks:
      - rinha

volumes:
  sockets:

networks:
  rinha:
    driver: bridge
