#ifndef RINHA_CONFIG_H
#define RINHA_CONFIG_H

#define RINHA_DEFAULT_ADDR ":8080"
#define RINHA_DEFAULT_LISTEN_MODE "tcp"
#define RINHA_DEFAULT_UNIX_SOCKET "/sockets/api.ctrl"
#define RINHA_DEFAULT_EXEC_MODE "per_connection"
#define RINHA_DEFAULT_WORKERS 1u
#define RINHA_DEFAULT_FD_QUEUE_SIZE 1024u
#define RINHA_DEFAULT_INDEX_PATH "/app/resources/index.bin"
#define RINHA_DEFAULT_INDEX_WARMUP "off"
#define RINHA_DEFAULT_INDEX_WARMUP_QUERIES 2048u
#define RINHA_DEFAULT_INDEX_MADVISE "false"
#define RINHA_DEFAULT_SEARCH_IMPL "scalar"
#define RINHA_DEFAULT_KDTREE_PATH "/app/resources/kdtree.bin"
#define RINHA_DEFAULT_KDTREE_REPAIR_POLICY "boundary23_far45"
#define RINHA_DEFAULT_IVF8_MAX_CANDIDATES 4096u
#define RINHA_DEFAULT_IVF8_PROBES 8u
#define RINHA_READ_BUFFER_BYTES 4096
#define RINHA_MAX_REQUEST_BYTES 8192
#define RINHA_LISTEN_BACKLOG 128

#endif
