#ifndef RINHA_CONFIG_H
#define RINHA_CONFIG_H

#define RINHA_DEFAULT_ADDR ":8080"
#define RINHA_DEFAULT_INDEX_PATH "/app/resources/index.bin"
#define RINHA_DEFAULT_IVF8_MAX_CANDIDATES 4096u
#define RINHA_DEFAULT_IVF8_PROBES 8u
#define RINHA_READ_BUFFER_BYTES 4096
#define RINHA_MAX_REQUEST_BYTES 8192
#define RINHA_LISTEN_BACKLOG 128

#endif
